# Homebrew formula for spm (Skill and Plugin Manager).
# Generated by scripts/build-homebrew.mjs — do not edit by hand.
class Spm < Formula
  desc "Skill and Plugin Manager — install AI-agent skills into every coding agent"
  homepage "https://github.com/hiadamhere/spm"
  version "0.3.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/hiadamhere/spm/releases/download/v0.3.4/spm-0.3.4-osx-arm64.tar.gz"
      sha256 "b786b852b5d48661d9c125f7c2b73be30a8f890c9399ded548302ee01e952c70"
    else
      url "https://github.com/hiadamhere/spm/releases/download/v0.3.4/spm-0.3.4-osx-x64.tar.gz"
      sha256 "6add40a3be0ab3611dde0342cc165fbbaa54981f3f45e305253f1d13c9bf3e0c"
    end
  end

  on_linux do
    url "https://github.com/hiadamhere/spm/releases/download/v0.3.4/spm-0.3.4-linux-x64.tar.gz"
    sha256 "bf0fb1bb869d3f7ca20f045bb4564c758306d89cfdf0549a9ca9597781eaebc7"
  end

  def install
    bin.install "spm"
  end

  test do
    assert_match "spm #{version}", shell_output("#{bin}/spm version")
  end
end
