# Homebrew formula for spm (Skill and Plugin Manager).
# Generated by scripts/build-homebrew.mjs — do not edit by hand.
class Spm < Formula
  desc "Skill and Plugin Manager — install AI-agent skills into every coding agent"
  homepage "https://github.com/hiadamhere/spm"
  version "0.4.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/hiadamhere/spm/releases/download/v0.4.0/spm-0.4.0-osx-arm64.tar.gz"
      sha256 "94fbce79a7934d0cc29c31ea01b25e6b520f54f29faabdc8fe228e0b936dc268"
    else
      url "https://github.com/hiadamhere/spm/releases/download/v0.4.0/spm-0.4.0-osx-x64.tar.gz"
      sha256 "4f4b581a2deeb83e37331de4186fc96efda49381c54693c717a4bfc2a46ba9df"
    end
  end

  on_linux do
    url "https://github.com/hiadamhere/spm/releases/download/v0.4.0/spm-0.4.0-linux-x64.tar.gz"
    sha256 "19255ceea80c4f13a60cacd3474c66b6fc87ecb407cbcdfabb14d4966a7de522"
  end

  def install
    bin.install "spm"
  end

  test do
    assert_match "spm #{version}", shell_output("#{bin}/spm version")
  end
end
